# Generated by Django 3.2.4 on 2021-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myword',
            name='mynote4review',
            field=models.CharField(default='None. To be updated.', max_length=500),
        ),
    ]
