# Generated by Django 3.2.4 on 2021-06-16 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title_name', models.CharField(blank=True, max_length=300, null=True)),
                ('title_number', models.IntegerField(blank=True, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_lower_case', models.TextField(blank=True, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('chapter_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_lower_case', models.TextField(blank=True, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('chapter_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.chapter')),
                ('paragraph_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.paragraph')),
            ],
        ),
    ]
