# Generated by Django 3.2.4 on 2021-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='paragraph_title',
        ),
    ]
