# Generated by Django 3.2.4 on 2021-06-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0003_delete_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Le Petit Prince', max_length=300)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
