# Generated by Django 3.2.4 on 2021-06-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0005_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='story_title',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='original_text.book'),
        ),
    ]
