# Generated by Django 3.2.4 on 2021-06-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0006_auto_20210625_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.book'),
        ),
    ]
