# Generated by Django 3.2.4 on 2021-06-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0007_alter_chapter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.sentence')),
                ('token_lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='original_text.lemma')),
            ],
        ),
    ]
