# Generated by Django 3.2.4 on 2021-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0008_lemma_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
