# Generated by Django 3.2.4 on 2021-06-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0010_auto_20210625_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='token_lemma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='original_text.lemma'),
            preserve_default=False,
        ),
    ]
