# Generated by Django 3.2.4 on 2021-06-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0011_auto_20210625_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='chapter_title',
            new_name='chapter_id',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='number',
        ),
    ]
