# Generated by Django 3.2.4 on 2021-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0013_rename_source_token_sentence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='token_total_french',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
