# Generated by Django 3.2.4 on 2021-06-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0014_sentence_token_total_french'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chapter_id',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='original_text.chapter'),
            preserve_default=False,
        ),
    ]
