# Generated by Django 3.2.4 on 2021-06-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0016_auto_20210627_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='lemma_language',
            field=models.CharField(default='french', max_length=100),
        ),
    ]
