# Generated by Django 3.2.4 on 2021-06-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('original_text', '0018_token_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='original_text.book'),
        ),
        migrations.AlterField(
            model_name='token',
            name='book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='original_text.book'),
        ),
    ]
