# Generated by Django 3.2.4 on 2021-06-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='raw_data/source/')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_lower_case', models.TextField(blank=True, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('source_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdata.source')),
            ],
        ),
    ]
