# Generated by Django 3.2.4 on 2021-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rawdata/source/'),
        ),
    ]
