# Generated by Django 3.2.4 on 2021-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0003_auto_20210618_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rawdata',
        ),
    ]
