# Generated by Django 3.2.4 on 2021-07-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rawdata', '0004_delete_rawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='raw_data/source/')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('chapter_id', models.IntegerField(blank=True, null=True)),
                ('sentence_id', models.IntegerField(blank=True, null=True)),
                ('sentence_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_lower_case', models.TextField(blank=True, null=True)),
                ('translation_eng', models.TextField(blank=True, null=True)),
                ('translation_chi', models.TextField(blank=True, null=True)),
                ('token_total_french', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='none', max_length=500)),
                ('priority', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('source_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdata.source')),
            ],
        ),
        migrations.CreateModel(
            name='NLP_token_Rawdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('chapter_id', models.IntegerField(blank=True, null=True)),
                ('sentence_id', models.IntegerField(blank=True, null=True)),
                ('sentence_number', models.IntegerField(blank=True, null=True)),
                ('sentence', models.CharField(blank=True, max_length=2000, null=True)),
                ('token_language', models.CharField(default='french', max_length=50)),
                ('nlp_text', models.CharField(blank=True, max_length=800, null=True)),
                ('nlp_lemma', models.CharField(blank=True, max_length=800, null=True)),
                ('nlp_pos', models.CharField(blank=True, max_length=800, null=True)),
                ('nlp_tag', models.CharField(blank=True, max_length=800, null=True)),
                ('nlp_dep', models.CharField(blank=True, max_length=800, null=True)),
                ('note', models.CharField(blank=True, max_length=800, null=True)),
                ('token_nunmber', models.IntegerField(blank=True, null=True)),
                ('vocab_frequency_score', models.IntegerField(blank=True, null=True)),
                ('notes_vocab_frequency_score', models.BooleanField(default=False)),
                ('source_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawdata.rawdata')),
            ],
        ),
    ]
