# Generated by Django 3.2.4 on 2021-07-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0005_lemma_nlp_token_rawdata_rawdata_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='source_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rawdata.source'),
        ),
    ]
